version: '3.8'

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=jsonplaceholder
      - POSTGRES_USER=jsonplaceholder
      - POSTGRES_PASSWORD=jsonplaceholder
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 